# GitHub Actions Workflow File
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Directory and file to compile
      DIR: .
      FILE: cv
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      # First, modify the LaTeX file to use a different font
      - name: Modify LaTeX to use available fonts
        run: |
          if [ -f ${{ env.DIR }}/${{ env.FILE }}.tex ]; then
            # Replace Arial with Liberation Sans (available in TeX Live)
            sed -i 's/\\setmainfont{Arial}/\\setmainfont{Liberation Sans}/g' ${{ env.DIR }}/${{ env.FILE }}.tex
            # Alternative replacements if needed
            sed -i 's/\\setsansfont{Arial}/\\setsansfont{Liberation Sans}/g' ${{ env.DIR }}/${{ env.FILE }}.tex
            sed -i 's/\\setmonofont{Arial}/\\setmonofont{Liberation Sans}/g' ${{ env.DIR }}/${{ env.FILE }}.tex
          fi
      
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}
          compiler: latexmk
          args: -xelatex
          extra_system_packages: "fonts-liberation"
          extra_font_packages: "texlive-fonts-recommended texlive-fonts-extra"
      
      - name: Move output PDF to artifacts folder
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: github_artifacts
      
      - name: Move artifact to deploy folder
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      
      - name: Deploy PDF on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
  
  copy-index-to-build:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy additional files to build branch
        uses: planetoftheweb/copy-to-branches@v1.3
        env:
          key: main
          files: index.html CNAME
